### ISSUE TITLE
Contribute for Hacktoberfest

### ISSUE THREAD

**Issue by Shams66789** [Shams66789/Hack#2]

**Comment by 0day-anon** [comment]
Can I add my Bubble sort algorithm in java to your repo?

**Comment by 0day-anon** [comment]
@Shams66789  its showing Ineligible Repository in my hacktoberfist profile.
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by Shams66789** [comment]
@Rupinderjeet2004  I don't know why this is happening. Even I am facing this problem in my PRs.

**Comment by 0day-anon** [comment]
Can you merge this PR and label this PR with "hacktoberfest-accepted"?

**Comment by 0day-anon** [comment]
after merging, now it's no longer Ineligible Repository. Thank you!

**Comment by Nikhil-Sharma-1** [comment]
@Shams66789 
1. Can we add any type of code in this repo?
2. Can we add code in any Language?

**Comment by Shams66789** [comment]
@Nikhil-Sharma-1  yes you can add any of your code and in any language which you are comfortable with.

**Comment by LaxmiNyamagoud** [comment]
@Shams66789 
I would like to contribute some C programs ,can you assign this work to me ?

**Comment by Shams66789** [comment]
Thank you all for contributing here
